---
- hosts: all
  tasks:
  - name: Install dotfiles
    copy:
      src={{ item }}
      dest=~/{{ item | regex_replace('^_(?P<name>.*)', '.\\g<name>') }}
    with_items:
    - _aliases
    - _gitconfig
    - _gitignore_global
    - _pythonrc
    - _tmux.conf
    - _vimrc
    - _zlogin
    - _zlogout
    - _zpreztorc
    - _zshenv
    - _zshrc

  - name: Create vim autoload directory
    file:
      state=directory
      path=~/.vim/autoload

  - name: Install plug for vim
    get_url:
      dest=~/.vim/autoload/plug.vim
      url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  - name: Install zprezto
    git:
      repo=https://github.com/schlueter/prezto.git
      dest=~/.zprezto
      version=master
