#!/usr/bin/env ansible-playbook --inventory vagrant.local.rf29.net,
---
- hosts: all
  gather_facts: yes
  vars:
    user: bschlueter
    prezto_repo: https://github.com/schlueter/prezto.git
    dotfiles_user: bschlueter
    dotfiles:
    - aliases
    - gitconfig
    - gitignore_global
    - pythonrc
    - tmux.conf
    - vimrc
    - zlogin
    - zlogout
    - zpreztorc
    - zshenv
    - zshrc
  roles:
  - hub
  - user-dotfiles
  - vim-plug
  - zsh-prezto
