#!/usr/bin/env ansible-playbook --inventory vagrant.local.rf29.net,
---
- hosts: all
  vars:
    user: jescobar
    dotfiles_user: jescobar
    dotfiles:
    - gitconfig
    - profile
    - vimrc
  roles:
  - user-dotfiles
