#!/usr/bin/env python

import argparse
import os
import sys
from subprocess import call


COMMAND='ls'
DIRECTORY_FILE='test.txt'

def main(directory_file=DIRECTORY_FILE, command=COMMAND):
    with directory_file:
        for line in directory_file:
            os.chdir(line.strip())
            call(command.split())
            os.chdir(os.pardir)

def parse_args():
    parser = argparse.ArgumentParser(description='Execute commands on a list of directories.')
    parser.add_argument('--command',
                        '-c',
                        type=str,
                        default=COMMAND,
                        help='the command to be run')
    parser.add_argument('--directory-file',
                        type=argparse.FileType('r'),
                        default=DIRECTORY_FILE,
                        help='a file containing a list of directories to run the command on')

    return parser.parse_args()


if __name__ == '__main__':
    args = parse_args()
    main(args.directory_file, args.command)
