#!/usr/bin/env ansible-playbook --inventory vagrant.local.rf29.net,
---
- hosts: all
  vars:
    user: tswift

    oh_my_zsh_repo: https://github.com/schlueter/oh-my-zsh.git
    oh_my_zsh_repo_branch: feature/blusch-theme

    dotfiles_user: tswift
    dotfiles: [ zshrc aliases vimrc ]

  roles:
  - user-dotfiles
  - vim-vundle
  - oh-my-zsh
  - hub

  tasks:
  - name: Add alias so that emoji will display with ls
    lineinfile:
      dest=~/.aliases
    args:
      line: alias ls='ls --show-control-chars'
