---
- name: Warn if no user specified
  debug: msg="No user specified with the user var, this may cause issues in other roles…"
  when: user is not defined

- name: Check for user
  command:
    getent passwd {{ user }}
  ignore_errors: yes
  changed_when: no
  when: ansible_system == "Linux"
  register: passwd

- name: Check for user
  command:
    id {{ user }}
  ignore_errors: yes
  changed_when: no
  when: ansible_system == "Darwin"
  register: passwd

- name: Fail if user does not exist
  fail: msg="User supplied as user does not exist."
  when: passwd|failed
