---
- name: Set dotfiles user to user if unspecified
  when: dotfiles_user is undefined
  set_fact:
    dotfiles_user: '{{ user }}'
  always_run: yes

- name: Install user's dotfiles
  copy:
    src={{ dotfiles_user | default('default') }}-{{ item }}
    dest=~/.{{ item }}
  with_items: "{{ dotfiles }}"

- name: Install explicit dotfiles
  copy:
    src={{ item }}
    dest=~/.{{ item | regex_replace('[-_\.]?(?P<name>.+)', '\\g<name>')}}
  with_items: "{{ dotfiles_by_user }}"

- name: Dotfile_urls deprecation
  debug: msg="dotfile_urls are no longer supported. Please add your dotfiles to this repo."
  when: dotfiles_urls | default(False)
  always_run: yes
