---
- name: Create vim autoload directory
  file:
    state=directory
    path=~/.vim/autoload

- name: Install plug for vim
  get_url:
    dest=~/.vim/autoload/plug.vim
    url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Use Plug to install plugins
  command: vim -c PlugInstall -c qa
